### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by AkshayM21** [19RyanA/CheckPCR#14]
I've encountered an bug.

```
Messsage: Cannot read property 'indexOf' of undefined
Stack: TypeError: Cannot read property 'indexOf' of undefined
    at display (chrome-extension://iofggienboopplgnobbjfafkcodclkpl/client.js:1236:23)
    at parse (chrome-extension://iofggienboopplgnobbjfafkcodclkpl/client.js:502:3)
    at chrome-extension://iofggienboopplgnobbjfafkcodclkpl/client.js:282:11
    at <anonymous>
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36
Version: 2.24.1
```

**Comment by rianadon** [comment]
Hi there! Sorry it's taken so long to get back to this.

I'm not really sure what the problem is.
Are you getting this error frequently or did it only happen once?

Thanks!

**Comment by AkshayM21** [comment]
So far it's only happened once.

**Comment by rianadon** [comment]
Okay. Eventually I'm going to refactor to code to make it easier to debug, but since this only happened once and I can't tell what could be causing the issue there isn't too much I can do.

I'll leave this issue open, and if you ever get the error again / can cause the error to occur again please post another comment.
