### ISSUE TITLE
Parsing Bug

### ISSUE THREAD

**Issue by jclin22009** [19RyanA/CheckPCR#17]
I've encountered an bug.

```
Messsage: Cannot read property 'indexOf' of undefined
Stack: TypeError: Cannot read property 'indexOf' of undefined
    at display (chrome-extension://mibpogcodkojknjlgjeckmakcigjodnp/client.js:1236:24)
    at parse (chrome-extension://mibpogcodkojknjlgjeckmakcigjodnp/client.js:502:3)
    at chrome-extension://mibpogcodkojknjlgjeckmakcigjodnp/client.js:282:11
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
Version: 2.24.3
```

**Comment by rianadon** [comment]
Thanks for reporting the bug @jclin22009!

Did this error message pop up the first time you opened Check PCR or after you spent some time clicking around within it?

Also I'm going to soon-ish be pushing an update which has some of the parsing code rewritten. Hopefully that shall correct the bug. If not it seems I'll have a bit of troubleshooting to do.

**Comment by jclin22009** [comment]
The bug spontaneously popped up today. I've been using CheckPCR for a while, and I didn't mess around with the source code.

**Comment by rianadon** [comment]
Wow that was a speedy reply!

I'm not sure at all what the source of the bug could be then. Does the error pop up every time you load the page or did it just happen once?

If it happens every time, would you have time to try out the version I have at the [typescript](https://github.com/rianadon/CheckPCR/tree/typescript) branch (either by re-downloading from GitHub or using a Git client to switch branches)?

Thanks again!
