### ISSUE TITLE
PCR Parsing error

### ISSUE THREAD

**Issue by AkshayM21** [19RyanA/CheckPCR#18]
I've encountered an bug.

```
Messsage: Cannot read property 'indexOf' of undefined
Stack: TypeError: Cannot read property 'indexOf' of undefined
    at display (chrome-extension://bgfabcdolnakhoioalgalampgaaphoei/client.js:1236:24)
    at parse (chrome-extension://bgfabcdolnakhoioalgalampgaaphoei/client.js:502:3)
    at chrome-extension://bgfabcdolnakhoioalgalampgaaphoei/client.js:363:11
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
Version: 2.24.3
```

**Comment by rianadon** [comment]
Hi Akshay!

I've made this error log more verbosely in the typescript branch of the repository.
If you could, it would be great if you could try that branch and report the error it gives.

Thanks!
