### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by yangrussell** [19RyanA/CheckPCR#19]
Hi. I opened CheckPCR and encountered this error.
```
Messsage: Cannot read property 'parentNode' of null
Stack: TypeError: Cannot read property 'parentNode' of null
    at parse (chrome-extension://dgmfnaeknojgajodfffkfadjoclbkolj/client.js:453:51)
    at chrome-extension://dgmfnaeknojgajodfffkfadjoclbkolj/client.js:282:11
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Version: 2.24.3
```

**Comment by rianadon** [comment]
Hi @yangrussell!

It looks like PCR is giving back a non-standard response.
The update I've just very recently pushed should give some extra information if it gets this error.
If the error occurs again after updating, would you be able to paste the new error?

Thanks!
