### ISSUE TITLE
A bug :o

### ISSUE THREAD

**Issue by lvinnn** [19RyanA/CheckPCR#21]
So I literally just opened pcr and this thing popped up. I don't remember doing anything wacky, but the last thing I remember doing besides looking at the hw was change one of the colors. It looks like it found my assignments, so it's just the color that's not working.

Also, the close button on the pop-up doesn't work

```
Message: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '.assignment.0 { background-color: {; }'.
Stack: Error: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '.assignment.0 { background-color: {; }'.
    at addColorRule (chrome-extension://keigdnfobajaopgfaeampfbokfaombjc/build/app-bundle.js:3285:15)
    at Object.entries.forEach (chrome-extension://keigdnfobajaopgfaeampfbokfaombjc/build/app-bundle.js:3294:13)
    at Array.forEach (<anonymous>)
    at updateColors (chrome-extension://keigdnfobajaopgfaeampfbokfaombjc/build/app-bundle.js:3293:42)
    at Object.<anonymous> (chrome-extension://keigdnfobajaopgfaeampfbokfaombjc/build/app-bundle.js:3306:1)
    at __webpack_require__ (chrome-extension://keigdnfobajaopgfaeampfbokfaombjc/build/app-bundle.js:20:30)
    at chrome-extension://keigdnfobajaopgfaeampfbokfaombjc/build/app-bundle.js:69:18
    at chrome-extension://keigdnfobajaopgfaeampfbokfaombjc/build/app-bundle.js:72:10
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Version: 2.25.0
```

**Comment by rianadon** [comment]
Hi there!

Thank you for taking the time to submit the bug report. With such a detailed report of what you did before! In fact, changing the colors is precisely what trips up the app and gives that error message.
Not too long ago, I pushed an update `2.25.1`, which should fix the bug.

Since I'm pretty sure the update resolves the error, I'm going to close the issue. If you still get the error message, feel free to reopen it.

Thanks!
