### ISSUE TITLE
bug!

### ISSUE THREAD

**Issue by AkshayM21** [19RyanA/CheckPCR#24]
I've encountered a bug.

```
Message: Could not find month view indicator (document title is 
	Error
)
Stack: Error: Could not find month view indicator (document title is 
	Error
)
    at parse (chrome-extension://nbemcenpbhhhfmfaoddmjbljodldlica/build/app-bundle.js:1387:15)
    at fetch (chrome-extension://nbemcenpbhhhfmfaoddmjbljodldlica/build/app-bundle.js:1175:17)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Version: 2.26.0
```

**Comment by rianadon** [comment]
Does this happen often? I have no idea why PCR sometimes gives an error page, but hopefully it's just something based on chance.
